# Generated by Django 4.0.3 on 2022-12-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='model',
        ),
        migrations.AddField(
            model_name='appointment',
            name='automobile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='service_rest.automobilevo'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='scheduled', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='service_rest.technician'),
        ),
    ]
