# Generated by Django 4.0.3 on 2022-12-08 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_remove_appointment_automobile_appointment_auto_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='auto_vin',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='service_rest.technician'),
        ),
    ]
