# Generated by Django 4.0.3 on 2022-12-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_apptstatus_remove_appointment_auto_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vin',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
