# Generated by Django 4.0.3 on 2022-12-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_appointment_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='scheduled', max_length=50),
        ),
        migrations.DeleteModel(
            name='ApptStatus',
        ),
    ]
