# Generated by Django 4.0.3 on 2022-12-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_appointment_vip_alter_appointment_appt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appt_date',
            field=models.DateField(default=['%m/%d/%y']),
        ),
    ]
