# Generated by Django 4.0.3 on 2022-12-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0011_alter_appointment_appt_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appt_time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_date',
            field=models.DateTimeField(default=['%Y-%m-%d %H:%M']),
        ),
    ]
